parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '8'
                charset: utf8mb4
                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    enum: string

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                #naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                mappings:
                    CodeChallenge:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: CodeChallenge