<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDKo95yM\CodeChallenge_Infrastructure_Symfony_KernelTestsDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDKo95yM/CodeChallenge_Infrastructure_Symfony_KernelTestsDebugContainer.php') {
    touch(__DIR__.'/ContainerDKo95yM.legacy');

    return;
}

if (!\class_exists(CodeChallenge_Infrastructure_Symfony_KernelTestsDebugContainer::class, false)) {
    \class_alias(\ContainerDKo95yM\CodeChallenge_Infrastructure_Symfony_KernelTestsDebugContainer::class, CodeChallenge_Infrastructure_Symfony_KernelTestsDebugContainer::class, false);
}

return new \ContainerDKo95yM\CodeChallenge_Infrastructure_Symfony_KernelTestsDebugContainer([
    'container.build_hash' => 'DKo95yM',
    'container.build_id' => '192d0863',
    'container.build_time' => 1673825897,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDKo95yM');
