version: '3'

services:
  db:
    container_name: siroko-mysql
    build:
      context: etc/dev/mysql
    volumes:
      - "./dumps/doctorslot.sql:/docker-entrypoint-initdb.d/doctorslot.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3315:3306"
  php:
    container_name: siroko-app
    build:
      context: etc/dev/php8-fpm
    volumes:
      - .:/var/www/app
      - ./logs:/var/logs

  nginx:
    container_name: siroko-nginx
    build:
      context: etc/dev/nginx
    ports:
      - "2138:80"
    volumes:
      - ./logs/nginx/:/var/log/nginx
