<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4TvKArC\Emn_CodeChallenge_Infrastructure_Symfony_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4TvKArC/Emn_CodeChallenge_Infrastructure_Symfony_KernelProdContainer.php') {
    touch(__DIR__.'/Container4TvKArC.legacy');

    return;
}

if (!\class_exists(Emn_CodeChallenge_Infrastructure_Symfony_KernelProdContainer::class, false)) {
    \class_alias(\Container4TvKArC\Emn_CodeChallenge_Infrastructure_Symfony_KernelProdContainer::class, Emn_CodeChallenge_Infrastructure_Symfony_KernelProdContainer::class, false);
}

return new \Container4TvKArC\Emn_CodeChallenge_Infrastructure_Symfony_KernelProdContainer([
    'container.build_hash' => '4TvKArC',
    'container.build_id' => '22701441',
    'container.build_time' => 1671641356,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4TvKArC');
