index:
    path: /
    controller: CodeChallenge\Infrastructure\Http\Controller\SiteController::status

products_in_shopping_cart:
    path: api/count
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::countProductsInCart
    methods: [GET]

add_to_shopping_cart:
    path: api/cart/add
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::add
    methods: [POST]

update_shopping_cart:
    path: api/cart/update
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::update
    methods: [PUT]

remove_from_shopping_cart:
    path: api/cart/delete
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::delete
    methods: [DELETE]

confirm_purchase:
    path: api/cart/confirm
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::confirmPurchase
    methods: [POST]
