index:
    path: /
    controller: CodeChallenge\Infrastructure\Http\Controller\SiteController::status

add_to_shopping_cart:
    path: api/add_to_shopping_cart/{productId}/{quantity}
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::add
    methods: [POST]

update_shopping_cart:
    path: api/update_shopping_cart/{productId}/{quantity}
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::update
    methods: [PUT]

remove_from_shopping_cart:
    path: api/remove_from_shopping_cart/{productId}
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::remove
    methods: [DELETE]

confirm_purchase:
    path: api/purchase
    controller: CodeChallenge\Infrastructure\Http\Controller\ShoppingCartController::confirmPurchase
    methods: [POST]
